[package]
name = "tetris"
version = "0.1.0"
authors = ["George White <me@galexite.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.15"
rand = "0.7"
